#!/usr/bin/env python3
"""
convert-to-bevy.py — Bevy 게임엔진용 handle/sprite 어트리뷰트 YAML 자동 생성

각 PNG 자산 옆에 .meta.yaml을 생성:
  texture: "elf_swordsman.png"
  size_px: [64, 64]
  anchor: center
  pivot: [0.5, 0.5]
  z_layer: 1
  handles:
    - race: elf
      unit: swordsman
      animations: ["idle", "attack", "walk"]
"""
import argparse, sys
from pathlib import Path

TEMPLATE = """# Auto-generated by convert-to-bevy.py
texture: "{filename}"
size_px: {size_px}
anchor: center
pivot: [0.5, 0.5]
z_layer: 1
category: "{category}"
source: "{src_rel}"
license: "{license}"
attribution: "{copyright}"
"""


def parse_filename(p: Path):
    name = p.stem  # "human_swordsman-attack-1"
    parts = name.split("-")
    return {
        "race": parts[0].split("_")[0] if "_" in parts[0] else parts[0],
        "anim": parts[-2] if len(parts) > 2 and any(a in name for a in ["attack","idle","walk","run","die","defend"]) else "idle",
    }


def img_dimensions(p: Path):
    """PNG/WebP 정확한 픽셀 차원 (Pillow 의존 없이 헤더만)"""
    try:
        with open(p, "rb") as f:
            head = f.read(64)
        if head[:8] == b"\x89PNG\r\n\x1a\n":
            w = int.from_bytes(head[16:20], "big")
            h = int.from_bytes(head[20:24], "big")
            return (w, h)
    except Exception:
        pass
    return (64, 64)  # fallback


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", required=True, type=Path)
    ap.add_argument("--limit", type=int, default=200)
    args = ap.parse_args()

    if not args.src.exists():
        print(f"❌ {args.src} 없음")
        sys.exit(1)

    image_exts = {".png", ".webp", ".jpg"}
    produced = 0
    for fp in args.src.rglob("*"):
        if not fp.is_file() or fp.suffix.lower() not in image_exts:
            continue
        if args.limit and produced >= args.limit:
            break

        meta = parse_filename(fp)
        w, h = img_dimensions(fp)

        out = fp.with_suffix(fp.suffix + ".meta.yaml")
        body = TEMPLATE.format(
            filename=fp.name,
            size_px=f"[{w}, {h}]",
            category=fp.relative_to(args.src).parts[0] if len(fp.relative_to(args.src).parts) > 1 else "asset",
            src_rel=str(fp.relative_to(args.src)),
            license="CC-BY-4.0",  # default for Wesnoth assets
            copyright="Battle for Wesnoth contributors",
        )
        out.write_text(body)
        produced += 1

    print(f"✅ {produced}개 Bevy .meta.yaml 생성")


if __name__ == "__main__":
    main()
